# Generated by Django 4.1.2 on 2023-11-27 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdtname', models.CharField(max_length=20)),
                ('prdtdescription', models.TextField()),
                ('prdtimg', models.ImageField(upload_to='')),
                ('prdtprice', models.IntegerField()),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comstore.categories')),
            ],
        ),
        migrations.DeleteModel(
            name='membersdb',
        ),
    ]
