# Generated by Django 4.1.2 on 2023-12-13 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comstore', '0006_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='subtotal',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('order_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comstore.orderdetails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comstore.product')),
            ],
        ),
    ]
